CREATE TABLE IF NOT EXISTS ma_seqs (
    seq_name      VARCHAR(64) NOT NULL,
    current_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
    prefix        VARCHAR(16) NOT NULL DEFAULT '',
    padding       TINYINT UNSIGNED NOT NULL DEFAULT 0,
    increment_by  INT UNSIGNED NOT NULL DEFAULT 1,
    seq_status    VARCHAR(32)  DEFAULT NULL,
    rpt_flg       VARCHAR(16)  DEFAULT NULL,
    kwords        VARCHAR(255) DEFAULT NULL,
    note          VARCHAR(500) DEFAULT NULL,
    status        VARCHAR(32)  DEFAULT 'ACTIVE',
    create_id     BIGINT UNSIGNED DEFAULT NULL,
    create_dt     DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    modify_id     BIGINT UNSIGNED DEFAULT NULL,
    modify_dt     DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_dt    DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (seq_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
