CREATE TABLE IF NOT EXISTS ma_seqs (
    seq_name      VARCHAR(64) NOT NULL,
    current_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
    prefix        VARCHAR(16) NOT NULL DEFAULT '',
    padding       TINYINT UNSIGNED NOT NULL DEFAULT 0,
    increment_by  INT UNSIGNED NOT NULL DEFAULT 1,
    modify_dt     DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (seq_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
