-- migration up
-- Seed sequence rows for the classroom aggregate. Boot-time auto-migrate
-- is disabled (see internal/bootstrap/app.go), so this file must be run
-- manually on each environment alongside 014/015/016.
INSERT INTO ma_seqs (seq_name, current_value, prefix, padding) VALUES
('classroom',            0, 'CL', 8),  -- classroom_id:            CL00000001...
('classroom_member',     0, 'CM', 8),  -- member_id:               CM00000001...
('classroom_invitation', 0, 'CI', 8);  -- invitation_id:           CI00000001...
