package classroomexercisesubmission

import "errors"

// Module-scoped sentinel errors. See conventions.md §Errors.
var (
	ErrAnswerLabelRequired                                               = errors.New("answer label is required")
	ErrAnswersRequired                                                   = errors.New("answers is required")
	ErrClassroomExerciseNotFound                                         = errors.New("classroom exercise not found")
	ErrClassroomExerciseSubmissionBotAdapterNotConfigured                = errors.New("classroom exercise submission: bot adapter is not configured")
	ErrClassroomExerciseIDRequired                                       = errors.New("classroom_exercise_id is required")
	ErrClassroomExerciseSubmissionIDRequired                             = errors.New("classroom_exercise_submission_id is required")
	ErrClassroomIDOrClassroomExerciseIDRequiredWhenListingAcrossProfiles = errors.New("classroom_id or classroom_exercise_id is required when listing across profiles")
	ErrDuplicateQuestionNumber                                           = errors.New("duplicate question_number")
	ErrExerciseHasNoQuestionsToGrade                                     = errors.New("exercise has no questions to grade")
	ErrExerciseNotAvailable                                              = errors.New("exercise is not available")
	ErrInvalidSortBy                                                     = errors.New("invalid sort_by")
	ErrInvalidSortOrder                                                  = errors.New("invalid sort_order")
	ErrInvalidSubmissionStatus                                           = errors.New("invalid submission status")
	ErrManagerRoleRequired                                               = errors.New("manager role required")
	ErrMembershipNotActive                                               = errors.New("membership is not active")
	ErrNilRequest                                                        = errors.New("nil request")
	ErrNotMemberOfThisClassroom                                          = errors.New("not a member of this classroom")
	ErrNoteTooLong                                                       = errors.New("note too long")
	ErrPrivateExerciseOnlyCreatorCanSubmit                               = errors.New("private exercise — only the creator can submit")
	ErrProfileDoesNotBelongToAuthenticatedUser                           = errors.New("profile does not belong to the authenticated user")
	ErrProfileNotFound                                                   = errors.New("profile not found")
	ErrProfileIDRequired                                                 = errors.New("profile_id is required")
	ErrProfileIDRequiredWhenUserOwnsMultipleProfiles                     = errors.New("profile_id is required when the user owns multiple profiles")
	ErrQuestionNumberMustBe0                                             = errors.New("question_number must be > 0")
	ErrSearchTooLong                                                     = errors.New("search too long")
	ErrSessionRequired                                                   = errors.New("session is required")
	ErrSubmissionAlreadyExists                                           = errors.New("submission already exists")
	ErrSubmissionNotFound                                                = errors.New("submission not found")
	ErrTooManyAnswers                                                    = errors.New("too many answers")
	ErrUidNotFoundFromSession                                            = errors.New("uid not found from session")
	ErrYouCanNotSubmitAfterEndTime                                       = errors.New("You can not submit after end time")
	ErrYouCanNotSubmitBeforeStartTime                                    = errors.New("You can not submit before start time")
)
