package status

const (
	UNKNOW       Code = 100
	OK           Code = 200
	SUCCESS      Code = 200
	CREATED      Code = 201
	FAIL         Code = 400
	UNAUTHORIZED Code = 401
	NOT_FOUND    Code = 404
	INTERNAL     Code = 500

	// User stauts
	USER_MISSING_ID           Code = 1000
	USER_INVALID_PARAMS       Code = 1001
	USER_INVALID_ID           Code = 1002
	USER_NOT_FOUND            Code = 1003
	USER_MISSING_NAME         Code = 1004
	USER_MISSING_EMAIL        Code = 1006
	USER_MISSING_PASSWORD     Code = 1013
	USER_INVALID_EMAIL        Code = 1007
	USER_EMAIL_ALREADY_EXISTS Code = 1012
	USER_MISSING_PHONE        Code = 1008
	USER_PHONE_ALREADY_EXISTS Code = 1011
	USER_INVALID_PHONE        Code = 1009
	USER_INVALID_ROLE         Code = 1019
	USER_INVALID_STATUS       Code = 1010

	// Device status
	DEVICE_INVALID_PARAMS Code = 1101
	DEVICE_MISSING_UUID   Code = 1102
	DEVICE_MISSING_NAME   Code = 1103
	DEVICE_BLOCKED        Code = 1104

	// Login status
	LOGIN_MISSING_PARAMETERS Code = 1201
	LOGIN_WRONG_CREDENTIALS  Code = 1202

	// Block status
	BLOCK_MISSING_TYPE  Code = 1301
	BLOCK_MISSING_VALUE Code = 1302
	BLOCK_INVALID_TYPE  Code = 1303

	// OTP status
	OTP_MISSING_PURPOSE    Code = 1401
	OTP_INVALID_PURPOSE    Code = 1402
	OTP_MISSING_IDENTIFIER Code = 1403
	OTP_MISSING_CODE       Code = 1404
	OTP_INVALID_CODE       Code = 1405
	OTP_STILL_ACTIVE       Code = 1406
	OTP_EXCEED_MAX_SEND    Code = 1407
	OTP_EXCEED_MAX_VERIFY  Code = 1408
	OTP_EXPIRED            Code = 1409
	OTP_NOT_ALLOWED        Code = 1410
	OTP_BLOCK_DEVICE       Code = 1411
	OTP_BLOCK_DEVICE_PHONE Code = 1412
	OTP_BLOCK_DEVICE_EMAIL Code = 1413

	// Grade status
	GRADE_MISSING_ID            Code = 1500
	GRADE_INVALID_PARAMS        Code = 1501
	GRADE_MISSING_LABEL         Code = 1502
	GRADE_MISSING_DESCRIPTION   Code = 1503
	GRADE_MISSING_DISPLAY_ORDER Code = 1504
	GRADE_NOT_FOUND             Code = 1505
	GRADE_ALREADY_EXISTS        Code = 1506
	GRADE_CANNOT_DELETE         Code = 1507

	// Level status
	LEVEL_INVALID_PARAMS        Code = 1601
	LEVEL_MISSING_LABEL         Code = 1602
	LEVEL_MISSING_DESCRIPTION   Code = 1603
	LEVEL_MISSING_DISPLAY_ORDER Code = 1604
	LEVEL_NOT_FOUND             Code = 1605
	LEVEL_ALREADY_EXISTS        Code = 1606
	LEVEL_CANNOT_DELETE         Code = 1607

	// Profile status
	PROFILE_INVALID_PARAMS   Code = 1701
	PROFILE_MISSING_UID      Code = 1702
	PROFILE_MISSING_GRADE    Code = 1703
	PROFILE_MISSING_SEMESTER Code = 1704
	PROFILE_NOT_FOUND        Code = 1705
	PROFILE_ALREADY_EXISTS   Code = 1706
	PROFILE_CANNOT_DELETE    Code = 1707
	PROFILE_INVALID_GRADE    Code = 1708
	PROFILE_INVALID_LEVEL    Code = 1709

	// User Latest Quiz status
	USER_LATEST_QUIZ_INVALID_PARAMS      Code = 1801
	USER_LATEST_QUIZ_NOT_FOUND           Code = 1802
	USER_LATEST_QUIZ_GET_LIST_FAILED     Code = 1803
	USER_LATEST_QUIZ_GET_FAILED          Code = 1804
	USER_LATEST_QUIZ_CREATE_FAILED       Code = 1805
	USER_LATEST_QUIZ_UPDATE_FAILED       Code = 1806
	USER_LATEST_QUIZ_DELETE_FAILED       Code = 1807
	USER_LATEST_QUIZ_FORCE_DELETE_FAILED Code = 1808
	USER_MISSING_QUIZ_ANSWERS            Code = 1809

	// User Quiz Assessment status
	USER_QUIZ_ASSESSMENT_INVALID_PARAMS      Code = 1851
	USER_QUIZ_ASSESSMENT_NOT_FOUND           Code = 1852
	USER_QUIZ_ASSESSMENT_GET_LIST_FAILED     Code = 1853
	USER_QUIZ_ASSESSMENT_GET_FAILED          Code = 1854
	USER_QUIZ_ASSESSMENT_CREATE_FAILED       Code = 1855
	USER_QUIZ_ASSESSMENT_UPDATE_FAILED       Code = 1856
	USER_QUIZ_ASSESSMENT_DELETE_FAILED       Code = 1857
	USER_QUIZ_ASSESSMENT_FORCE_DELETE_FAILED Code = 1858

	// Semester status
	SEMESTER_MISSING_ID          Code = 1900
	SEMESTER_INVALID_PARAMS      Code = 1901
	SEMESTER_MISSING_NAME        Code = 1902
	SEMESTER_MISSING_DESCRIPTION Code = 1903
	SEMESTER_NOT_FOUND           Code = 1904
	SEMESTER_ALREADY_EXISTS      Code = 1905
	SEMESTER_CANNOT_DELETE       Code = 1906

	// Contact status
	CONTACT_EMAIL_MISSING    Code = 2001
	CONTACT_EMAIL_INVALID    Code = 2002
	CONTACT_PHONE_INVALID    Code = 2003
	CONTACT_NAME_MISSING     Code = 2004
	CONTACT_MESSAGE_TOO_LONG Code = 2005
	CONTACT_NAME_TOO_LONG    Code = 2006
	CONTACT_EMAIL_TOO_LONG   Code = 2007
	CONTACT_MESSAGE_MISSING  Code = 2008
)
