CREATE TABLE `ma_domains` (
  `id` char(36) NOT NULL COMMENT 'Primary key (UUID) identifying a business domain / tenant',
  `domain_name` varchar(255) DEFAULT NULL COMMENT 'Human-readable domain name (e.g. math.com)',
  `reverse_name` varchar(255) DEFAULT NULL COMMENT 'Reverse domain notation used as a unique identifier (e.g. com.math)',
  `note` varchar(500) DEFAULT NULL COMMENT 'Optional description or internal note about the domain',
  `domain_status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'Business status of the domain (ACTIVE, INACTIVE, SUSPENDED)',
  `status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'System-level record status (ACTIVE, DELETED, ARCHIVED)',
  `create_id` int DEFAULT '0' COMMENT 'User or system ID that created this record',
  `create_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Timestamp when the record was created',
  `modify_id` int DEFAULT '0' COMMENT 'User or system ID that last modified this record',
  `modify_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Timestamp of last modification',
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain_name` (`domain_name`),
  UNIQUE KEY `reverse_name` (`reverse_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ma_domains` (id, domain_name, reverse_name, domain_status, status, create_id, create_dt, modify_id, modify_dt)
VALUES('ebfcd9c4-ecad-11f0-882a-4e0736fd52a4', 'math.com', 'com.math', 'ACTIVE', 'ACTIVE', 0, CURRENT_TIMESTAMP(6), 0, CURRENT_TIMESTAMP(6));

CREATE TABLE `ma_pay_providers` (
  `id` char(36) NOT NULL COMMENT 'Primary key (UUID) for the payment provider configuration',
  `domain_id` char(36) NOT NULL COMMENT 'Foreign key referencing ma_domains.id',
  `provider_code` varchar(32) DEFAULT NULL COMMENT 'Logical provider code (Stripe, Cybersource, Plaid, Goat)',
  `provider_name` varchar(255) DEFAULT NULL COMMENT 'Display name of the payment provider',
  `merchant_id` varchar(255) DEFAULT NULL COMMENT 'Merchant identifier assigned by the payment provider',
  `api_key` varchar(255) DEFAULT NULL COMMENT 'Public or client API key for the provider',
  `api_secret` varchar(255) DEFAULT NULL COMMENT 'Secret key for authenticating API calls (should be encrypted)',
  `debit_mode` varchar(32) DEFAULT NULL COMMENT 'Debit card support status (LIVE, TEST, OFF)',
  `credit_mode` varchar(32) DEFAULT NULL COMMENT 'Credit card support status (LIVE, TEST, OFF)',
  `ach_mode` varchar(32) DEFAULT NULL COMMENT 'Bank / ACH support status (LIVE, TEST, OFF)',
  `crypto_mode` varchar(32) DEFAULT NULL COMMENT 'Crypto payment support status (LIVE, TEST, OFF)',
  `note` varchar(500) DEFAULT NULL COMMENT 'Optional internal notes or configuration comments',
  `pay_provider_status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'Business status of the provider integration',
  `status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'System-level record status',
  `create_id` int DEFAULT '0' COMMENT 'Creator user/system ID',
  `create_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Record creation timestamp',
  `modify_id` int DEFAULT '0' COMMENT 'Last modifier user/system ID',
  `modify_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain_provider_unique` (`domain_id`,`provider_code`),
  UNIQUE KEY `provider_api_unique` (`provider_code`,`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ma_pay_providers` (id,domain_id,provider_code,provider_name,merchant_id,api_key,api_secret,debit_mode,credit_mode,ach_mode,crypto_mode,pay_provider_status,note,status,create_id,create_dt,modify_id,modify_dt) VALUES
	 (UUID(),'ebfcd9c4-ecad-11f0-882a-4e0736fd52a4','Cybersource','cybersource','i247_test_1720426956','6566513f-649a-4431-bd34-2c4031177c25','hide_secret','LIVE','LIVE','OFF','OFF','ACTIVE',NULL,'ACTIVE',0,'2025-09-03 14:28:24',0,'2025-09-03 14:28:24'),
	 (UUID(),'ebfcd9c4-ecad-11f0-882a-4e0736fd52a4','Goat','goat',NULL,'yMKsknaLXvZ5BEYTP779UtB5IWXYykRR','hide_secret','LIVE','LIVE','OFF','OFF','ACTIVE',NULL,'ACTIVE',0,'2025-09-03 14:28:24',0,'2025-09-03 14:28:24'),
	 (UUID(),'ebfcd9c4-ecad-11f0-882a-4e0736fd52a4','Plaid','plaid',NULL,'68086a38ddca0b002030caec','hide_secret','OFF','OFF','LIVE','OFF','ACTIVE',NULL,'ACTIVE',0,'2025-09-03 14:28:24',0,'2025-09-03 14:28:24'),
	 (UUID(),'ebfcd9c4-ecad-11f0-882a-4e0736fd52a4','Stripe','stripe',NULL,'NOTYET','hide_secret','OFF','OFF','OFF','OFF','INACTIVE',NULL,'INACTIVE',0,'2025-09-03 14:28:24',0,'2025-09-03 14:28:24');


CREATE TABLE `ma_pay_customers` (
  `id` char(36) NOT NULL COMMENT 'Primary key (UUID) for payment customer record',
  `domain_id` char(36) NOT NULL COMMENT 'Tenant/domain this customer belongs to',
  `provider_id` char(36) NOT NULL COMMENT 'Payment provider used for this customer',
  `uid` char(36) NOT NULL COMMENT 'Internal system user/customer identifier',
  `pay_customer_token` varchar(100) DEFAULT NULL COMMENT 'Provider-side customer token or ID',
  `customer_name` varchar(255) DEFAULT NULL COMMENT 'Customer full name',
  `customer_email` varchar(255) DEFAULT NULL COMMENT 'Customer email address',
  `customer_phone` varchar(32) DEFAULT NULL COMMENT 'Customer phone number',
  `address_line1` varchar(255) DEFAULT NULL COMMENT 'Billing address line 1',
  `address_line2` varchar(255) DEFAULT NULL COMMENT 'Billing address line 2',
  `city_code` varchar(50) DEFAULT NULL COMMENT 'City or locality',
  `state_code` varchar(50) DEFAULT NULL COMMENT 'State or province',
  `zip_code` varchar(50) DEFAULT NULL COMMENT 'Postal or ZIP code',
  `country_code` varchar(50) DEFAULT NULL COMMENT 'ISO country code',
  `note` varchar(500) DEFAULT NULL COMMENT 'Optional notes about the customer',
  `pay_customer_status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'Payment-related customer status',
  `status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'System-level record status',
  `create_id` int DEFAULT '0' COMMENT 'Creator ID',
  `create_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Creation timestamp',
  `modify_id` int DEFAULT '0' COMMENT 'Last modifier ID',
  `modify_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ma_pay_methods` (
  `id` char(36) NOT NULL COMMENT 'Primary key (UUID) for payment method',
  `domain_id` char(36) NOT NULL COMMENT 'Tenant/domain identifier',
  `provider_id` char(36) NOT NULL COMMENT 'Payment provider associated with this method',
  `customer_id` char(36) NOT NULL COMMENT 'Reference to ma_pay_customers.id',
  `uid` int DEFAULT NULL COMMENT 'Internal user ID',
  `pay_access_token` varchar(80) DEFAULT NULL COMMENT 'Short-lived access token (if required by provider)',
  `pay_method_token` varchar(100) DEFAULT NULL COMMENT 'Provider-issued token representing the payment method',
  `pay_method_type` varchar(50) DEFAULT NULL COMMENT 'Payment method type (CREDIT_CARD, DEBIT_CARD, BANK_ACCOUNT)',
  `card_network` varchar(50) DEFAULT NULL COMMENT 'Card network (Visa, MasterCard, Amex)',
  `card_last4` varchar(10) DEFAULT NULL COMMENT 'Last 4 digits of card number',
  `is_default` tinyint(1) DEFAULT '0' COMMENT 'Indicates default payment method for the customer',
  `account_checksum` varchar(255) DEFAULT NULL COMMENT 'Hashed checksum for duplicate account detection',
  `card_exp_month` varchar(5) DEFAULT NULL COMMENT 'Card expiration month',
  `card_exp_year` varchar(5) DEFAULT NULL COMMENT 'Card expiration year',
  `issuer` varchar(80) DEFAULT NULL COMMENT 'Card issuing bank',
  `bank_routing_number` varchar(50) DEFAULT NULL COMMENT 'Bank routing number (tokenized or masked)',
  `bank_account_number` varchar(50) DEFAULT NULL COMMENT 'Bank account number (tokenized or masked)',
  `bank_account_type` varchar(50) DEFAULT NULL COMMENT 'Checking or Savings',
  `address_line1` varchar(255) DEFAULT NULL COMMENT 'Billing address line 1',
  `address_line2` varchar(255) DEFAULT NULL COMMENT 'Billing address line 2',
  `city_code` varchar(50) DEFAULT NULL COMMENT 'Billing city',
  `state_code` varchar(50) DEFAULT NULL COMMENT 'Billing state',
  `zip_code` varchar(50) DEFAULT NULL COMMENT 'Billing ZIP/postal code',
  `country_code` varchar(50) DEFAULT NULL COMMENT 'Billing country',
  `payment_type_id` int DEFAULT NULL COMMENT 'Internal payment type reference',
  `last_active` datetime DEFAULT NULL COMMENT 'Last successful usage timestamp',
  `note` varchar(500) DEFAULT NULL COMMENT 'Additional notes',
  `pay_method_status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'Payment method business status',
  `status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'System-level record status',
  `create_id` int DEFAULT '0' COMMENT 'Creator ID',
  `create_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Creation timestamp',
  `modify_id` int DEFAULT '0' COMMENT 'Last modifier ID',
  `modify_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `ma_pay_transactions` (
  `id` char(36) NOT NULL COMMENT 'Primary key (UUID) for the transaction',
  `domain_id` char(36) NOT NULL COMMENT 'Tenant/domain identifier',
  `provider_id` char(36) NOT NULL COMMENT 'Payment provider handling the transaction',
  `customer_id` char(36) NOT NULL COMMENT 'Reference to ma_pay_customers.id',
  `uid` char(36) NOT NULL COMMENT 'Internal user/customer identifier',
  `idempotency_key` varchar(255) DEFAULT NULL COMMENT 'Unique key to prevent duplicate transaction execution',
  `ref_no` varchar(100) DEFAULT NULL COMMENT 'Internal reference number',
  `pay_type` varchar(100) DEFAULT NULL COMMENT 'Transaction type (AUTHORIZE, CAPTURE, REFUND, VOID, REVERSE)',
  `pay_amount` varchar(50) DEFAULT NULL COMMENT 'Transaction amount',
  `pay_currency` varchar(10) DEFAULT NULL COMMENT 'ISO currency code (USD, EUR, etc.)',
  `method_id` char(36) NOT NULL COMMENT 'Reference to ma_pay_methods.id',
  `pay_method_token` varchar(100) DEFAULT NULL COMMENT 'Provider token used during transaction',
  `pay_id` varchar(100) DEFAULT NULL COMMENT 'Internal payment ID',
  `pay_ppid` varchar(100) DEFAULT NULL COMMENT 'Provider payment ID',
  `auth_code` varchar(50) DEFAULT NULL COMMENT 'Authorization code returned by provider',
  `pay_status` varchar(50) DEFAULT NULL COMMENT 'Transaction status (PENDING, SUCCESS, FAILED)',
  `pay_response` JSON DEFAULT NULL COMMENT 'Raw provider API response for auditing and debugging',
  `pay_date` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Transaction timestamp',
  `note` varchar(500) DEFAULT NULL COMMENT 'Optional transaction notes',
  `pay_transaction_status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'Business status of the transaction',
  `status` varchar(32) DEFAULT 'ACTIVE' COMMENT 'System-level record status',
  `create_id` int DEFAULT '0' COMMENT 'Creator ID',
  `create_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Creation timestamp',
  `modify_id` int DEFAULT '0' COMMENT 'Last modifier ID',
  `modify_dt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_idempotency_key` (`idempotency_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
