package status

type StatusCode int

const (
	SUCCESS               StatusCode = 200
	CREATED               StatusCode = 201
	ACCEPTED              StatusCode = 202
	NO_DATA               StatusCode = 202
	NO_CONTENT            StatusCode = 204
	BAD_REQUEST           StatusCode = 400
	FAIL                  StatusCode = 400
	UNAUTHORIZED          StatusCode = 401
	FORBIDDEN             StatusCode = 403
	NOT_FOUND             StatusCode = 404
	CONFLICT              StatusCode = 409
	INTERNAL_SERVER_ERROR StatusCode = 500

	USER_MISSING_EMAIL            StatusCode = 4001
	USER_MISSING_PHONE            StatusCode = 4002
	USER_MISSING_PASSWORD         StatusCode = 4003
	USER_INVALID_EMAIL            StatusCode = 4004
	USER_INVALID_PASSWORD         StatusCode = 4005
	USER_NOT_FOUND                StatusCode = 4006
	USER_EMAIL_ALREADY_EXISTS     StatusCode = 4007
	USER_PHONE_ALREADY_EXISTS     StatusCode = 4008
	USER_ALREADY_EXISTS           StatusCode = 4009
	USER_USERNAME_ALREADY_EXISTS  StatusCode = 4010
	USER_MISSING_NAME             StatusCode = 4011
	USER_AVATAR_INVALID_FILE      StatusCode = 4012
	USER_AVATAR_UPLOAD_FAILED     StatusCode = 4013
	USER_AVATAR_CONFLICT          StatusCode = 4014
	USER_AVATAR_INVALID_REFERENCE StatusCode = 4015
	USER_INVALID_ROLE             StatusCode = 4016

	AUTH_MISSING_LOGIN_NAME        StatusCode = 4201
	AUTH_MISSING_DEVICE_UUID       StatusCode = 4202
	AUTH_MISSING_IP_ADDRESS        StatusCode = 4203
	AUTH_MISSING_DEVICE_PUSH_TOKEN StatusCode = 4204
	AUTH_INVALID_TOKEN             StatusCode = 4205
	AUTH_LOGIN_FAILED              StatusCode = 4206
	AUTH_LOGOUT_FAILED             StatusCode = 4207

	PROFILE_NOT_FOUND                StatusCode = 4101
	PROFILE_MISSING_NAME             StatusCode = 4102
	PROFILE_MISSING_USER_ID          StatusCode = 4103
	PROFILE_MISSING_GRADE_ID         StatusCode = 4104
	PROFILE_MISSING_SEMESTER_ID      StatusCode = 4105
	PROFILE_INVALID_DOB              StatusCode = 4106
	PROFILE_AVATAR_INVALID_FILE      StatusCode = 4107
	PROFILE_AVATAR_UPLOAD_FAILED     StatusCode = 4108
	PROFILE_MISSING_PROGRAM_ID       StatusCode = 4109
	PROFILE_INVALID_LANGUAGE         StatusCode = 4110
	PROFILE_AVATAR_CONFLICT          StatusCode = 4111
	PROFILE_AVATAR_INVALID_REFERENCE StatusCode = 4112
	PROFILE_CODE_TAKEN               StatusCode = 4113
	PROFILE_CODE_GENERATION_FAILED   StatusCode = 4114

	PROGRAM_NOT_FOUND                  StatusCode = 4301
	PROGRAM_INVALID_LANGUAGE           StatusCode = 4302
	PROGRAM_MISSING_ID                 StatusCode = 4303
	PROGRAM_MISSING_LABEL              StatusCode = 4304
	PROGRAM_MISSING_DESCRIPTION        StatusCode = 4305
	PROGRAM_INVALID_DISPLAY_ORDER      StatusCode = 4306
	PROGRAM_INVALID_TRANSLATION        StatusCode = 4307
	PROGRAM_TRANSLATION_ALREADY_EXISTS StatusCode = 4308
	PROGRAM_TRANSLATION_NOT_FOUND      StatusCode = 4309

	GRADE_NOT_FOUND                  StatusCode = 4401
	GRADE_INVALID_LANGUAGE           StatusCode = 4402
	GRADE_MISSING_ID                 StatusCode = 4403
	GRADE_MISSING_LABEL              StatusCode = 4404
	GRADE_MISSING_DESCRIPTION        StatusCode = 4405
	GRADE_INVALID_DISPLAY_ORDER      StatusCode = 4406
	GRADE_INVALID_TRANSLATION        StatusCode = 4407
	GRADE_TRANSLATION_ALREADY_EXISTS StatusCode = 4408
	GRADE_TRANSLATION_NOT_FOUND      StatusCode = 4409

	SEMESTER_NOT_FOUND                  StatusCode = 4501
	SEMESTER_INVALID_LANGUAGE           StatusCode = 4502
	SEMESTER_MISSING_ID                 StatusCode = 4503
	SEMESTER_MISSING_NAME               StatusCode = 4504
	SEMESTER_MISSING_DESCRIPTION        StatusCode = 4505
	SEMESTER_INVALID_DISPLAY_ORDER      StatusCode = 4506
	SEMESTER_INVALID_TRANSLATION        StatusCode = 4507
	SEMESTER_TRANSLATION_ALREADY_EXISTS StatusCode = 4508
	SEMESTER_TRANSLATION_NOT_FOUND      StatusCode = 4509

	DEVICE_NOT_FOUND         StatusCode = 4601
	DEVICE_MISSING_UUID      StatusCode = 4602
	DEVICE_MISSING_NAME      StatusCode = 4603
	DEVICE_MISSING_USER_ID   StatusCode = 4604
	DEVICE_NOT_OWNED         StatusCode = 4605
	DEVICE_ALREADY_VERIFIED  StatusCode = 4606
	DEVICE_REGISTRATION_FAIL StatusCode = 4607
	DEVICE_VERIFICATION_FAIL StatusCode = 4608
	DEVICE_REVOKE_FAIL       StatusCode = 4609
	DEVICE_2FA_REQUIRED      StatusCode = 4610

	SCHOOL_NOT_FOUND            StatusCode = 4901
	SCHOOL_MISSING_ID           StatusCode = 4902
	SCHOOL_MISSING_NAME         StatusCode = 4903
	SCHOOL_NAME_TOO_LONG        StatusCode = 4904
	SCHOOL_INVALID_STATUS       StatusCode = 4905
	SCHOOL_DESCRIPTION_TOO_LONG StatusCode = 4906
	SCHOOL_PROFILE_LINK_FAILED  StatusCode = 4907

	CHAPTER_NOT_FOUND                  StatusCode = 4801
	CHAPTER_MISSING_ID                 StatusCode = 4802
	CHAPTER_MISSING_PROGRAM_ID         StatusCode = 4803
	CHAPTER_MISSING_GRADE_ID           StatusCode = 4804
	CHAPTER_MISSING_SEMESTER_ID        StatusCode = 4812
	CHAPTER_MISSING_LABEL              StatusCode = 4805
	CHAPTER_MISSING_DESCRIPTION        StatusCode = 4806
	CHAPTER_INVALID_DISPLAY_ORDER      StatusCode = 4807
	CHAPTER_INVALID_LANGUAGE           StatusCode = 4808
	CHAPTER_INVALID_TRANSLATION        StatusCode = 4809
	CHAPTER_TRANSLATION_ALREADY_EXISTS StatusCode = 4810
	CHAPTER_TRANSLATION_NOT_FOUND      StatusCode = 4811

	OTP_NOT_FOUND           StatusCode = 4701
	OTP_MISSING_TYPE        StatusCode = 4702
	OTP_MISSING_IDENTIFIER  StatusCode = 4703
	OTP_MISSING_CODE        StatusCode = 4704
	OTP_INVALID_TYPE        StatusCode = 4705
	OTP_INVALID_CODE        StatusCode = 4706
	OTP_EXPIRED             StatusCode = 4707
	OTP_ALREADY_VERIFIED    StatusCode = 4708
	OTP_REVOKED             StatusCode = 4709
	OTP_TOO_MANY_ATTEMPTS   StatusCode = 4710
	OTP_TOO_FREQUENT        StatusCode = 4711
	OTP_RATE_LIMITED        StatusCode = 4712
	OTP_DELIVERY_FAILED     StatusCode = 4713
	OTP_NO_DELIVERY_CHANNEL StatusCode = 4714
	OTP_GENERATION_FAILED   StatusCode = 4715
	OTP_DISABLED            StatusCode = 4716

	NOTIFICATION_MISSING_UID        StatusCode = 5001
	NOTIFICATION_MISSING_TITLE      StatusCode = 5002
	NOTIFICATION_MISSING_SHORT_TEXT StatusCode = 5003
	NOTIFICATION_INVALID_ICON       StatusCode = 5004
	NOTIFICATION_INVALID_PRIORITY   StatusCode = 5005
	NOTIFICATION_NOT_FOUND          StatusCode = 5006
	NOTIFICATION_SEND_FAILED        StatusCode = 5007
	NOTIFICATION_NO_DEVICE_TOKEN    StatusCode = 5008
	NOTIFICATION_DISABLED           StatusCode = 5009
	NOTIFICATION_NOT_OWNED          StatusCode = 5010
	NOTIFICATION_CONFIG_INVALID     StatusCode = 5011
	NOTIFICATION_CONNECT_FAILED     StatusCode = 5012

	MESSAGING_PUBLISH_FAILED   StatusCode = 6001
	MESSAGING_INVALID_ENVELOPE StatusCode = 6002
	MESSAGING_CONFIG_INVALID   StatusCode = 6003
	MESSAGING_CONNECT_FAILED   StatusCode = 6004

	CACHE_CONNECT_FAILED   StatusCode = 7001
	CACHE_CONFIG_INVALID   StatusCode = 7002
	CACHE_OP_FAILED        StatusCode = 7003
	CACHE_SERIALIZE_FAILED StatusCode = 7004

	STORAGE_CONFIG_INVALID StatusCode = 8001

	SMS_CONNECT_FAILED   StatusCode = 9001
	SMS_CONFIG_INVALID   StatusCode = 9002
	SMS_OP_FAILED        StatusCode = 9003
	SMS_SERIALIZE_FAILED StatusCode = 9004

	BOT_CONNECT_FAILED    StatusCode = 10001
	BOT_CONFIG_INVALID    StatusCode = 10002
	BOT_OP_FAILED         StatusCode = 10003
	BOT_SERIALIZE_FAILED  StatusCode = 10004
	BOT_INVALID_PROMPT    StatusCode = 10005
	BOT_CONTEXT_TOO_LARGE StatusCode = 10006
	BOT_RATE_LIMITED      StatusCode = 10007
	BOT_UNSUPPORTED_OP    StatusCode = 10008

	QUIZ_NOT_FOUND              StatusCode = 11001
	QUIZ_MISSING_PROFILE_ID     StatusCode = 11002
	QUIZ_MISSING_TYPE           StatusCode = 11003
	QUIZ_INVALID_TYPE           StatusCode = 11004
	QUIZ_INVALID_LANGUAGE       StatusCode = 11005
	QUIZ_MISSING_ANSWERS        StatusCode = 11006
	QUIZ_INVALID_ANSWERS        StatusCode = 11007
	QUIZ_ALREADY_SUBMITTED      StatusCode = 11008
	QUIZ_NOT_OWNED              StatusCode = 11009
	QUIZ_PREVIOUS_NOT_FOUND     StatusCode = 11010
	QUIZ_PREVIOUS_NOT_GRADED    StatusCode = 11011
	QUIZ_GENERATION_FAILED      StatusCode = 11012
	QUIZ_GRADING_FAILED         StatusCode = 11013
	QUIZ_PROFILE_NOT_CONFIGURED StatusCode = 11014
	QUIZ_INVALID_TYPE_OF_QUIZ   StatusCode = 11015
	QUIZ_ANSWER_SCHEMA_INVALID  StatusCode = 11016

	JOB_NOT_FOUND           StatusCode = 12001
	JOB_ALREADY_PAUSED      StatusCode = 12002
	JOB_NOT_PAUSED          StatusCode = 12003
	JOB_IN_FLIGHT           StatusCode = 12004
	JOB_RUNTIME_UNAVAILABLE StatusCode = 12005
	JOB_MISSING_NAME        StatusCode = 12006
	JOB_TRIGGER_FAILED      StatusCode = 12007
	TASK_HANDLER_NOT_FOUND  StatusCode = 12008
	TASK_QUEUE_FULL         StatusCode = 12009
	TASK_MISSING_NAME       StatusCode = 12010
	TASK_ENQUEUE_FAILED     StatusCode = 12011

	SEQ_NOT_FOUND         StatusCode = 12101
	SEQ_MISSING_NAME      StatusCode = 12102
	SEQ_GENERATION_FAILED StatusCode = 12103

	CLASSROOM_NOT_FOUND                    StatusCode = 12201
	CLASSROOM_MISSING_ID                   StatusCode = 12202
	CLASSROOM_MISSING_NAME                 StatusCode = 12203
	CLASSROOM_NAME_TOO_LONG                StatusCode = 12204
	CLASSROOM_DESCRIPTION_TOO_LONG         StatusCode = 12205
	CLASSROOM_MISSING_OWNER_PROFILE_ID     StatusCode = 12206
	CLASSROOM_INVALID_OWNER_ROLE           StatusCode = 12207
	CLASSROOM_INVALID_PROGRAM              StatusCode = 12208
	CLASSROOM_INVALID_GRADE                StatusCode = 12209
	CLASSROOM_ALREADY_ARCHIVED             StatusCode = 12210
	CLASSROOM_NOT_ARCHIVED                 StatusCode = 12211
	CLASSROOM_ALREADY_DELETED              StatusCode = 12212
	CLASSROOM_MAX_MEMBERS_REACHED          StatusCode = 12213
	CLASSROOM_CODE_INVALID                 StatusCode = 12214
	CLASSROOM_CODE_EXPIRED                 StatusCode = 12215
	CLASSROOM_CODE_DISABLED                StatusCode = 12216
	CLASSROOM_CODE_GENERATION_FAILED       StatusCode = 12217
	CLASSROOM_PERMISSION_DENIED            StatusCode = 12218
	CLASSROOM_OWNER_CANNOT_LEAVE           StatusCode = 12219
	CLASSROOM_OWNER_TRANSFER_TO_NON_MEMBER StatusCode = 12220
	CLASSROOM_INVALID_MAX_MEMBERS          StatusCode = 12221
	CLASSROOM_INVALID_SCHOOL               StatusCode = 12222
	CLASSROOM_CODE_TAKEN                   StatusCode = 12223
	CLASSROOM_PROGRAM_DUPLICATE            StatusCode = 12224

	// Profile-learning-progress (002-profile-learning-progress).
	CLASSROOM_PROGRESS_INVALID_DATE_RANGE StatusCode = 12225
	CLASSROOM_PROGRESS_INVALID_TZ         StatusCode = 12226
	CLASSROOM_PROGRESS_INVALID_PURPOSE    StatusCode = 12227

	CLASSROOM_MEMBER_NOT_FOUND            StatusCode = 12301
	CLASSROOM_MEMBER_MISSING_ID           StatusCode = 12302
	CLASSROOM_MEMBER_MISSING_CLASSROOM_ID StatusCode = 12303
	CLASSROOM_MEMBER_MISSING_PROFILE_ID   StatusCode = 12304
	CLASSROOM_MEMBER_ALREADY_MEMBER       StatusCode = 12305
	CLASSROOM_MEMBER_NOT_MEMBER           StatusCode = 12306
	CLASSROOM_MEMBER_INVALID_ROLE         StatusCode = 12307
	CLASSROOM_MEMBER_CANNOT_REMOVE_OWNER  StatusCode = 12308
	CLASSROOM_MEMBER_CANNOT_DEMOTE_OWNER  StatusCode = 12309

	CLASSROOM_INVITATION_NOT_FOUND               StatusCode = 12401
	CLASSROOM_INVITATION_MISSING_ID              StatusCode = 12402
	CLASSROOM_INVITATION_MISSING_TARGET          StatusCode = 12403
	CLASSROOM_INVITATION_INVALID_IDENTIFIER      StatusCode = 12404
	CLASSROOM_INVITATION_INVALID_IDENTIFIER_TYPE StatusCode = 12405
	CLASSROOM_INVITATION_INVALID_ROLE            StatusCode = 12406
	CLASSROOM_INVITATION_ALREADY_RESPONDED       StatusCode = 12407
	CLASSROOM_INVITATION_EXPIRED                 StatusCode = 12408
	CLASSROOM_INVITATION_NOT_PENDING             StatusCode = 12409
	CLASSROOM_INVITATION_NOT_INVITEE             StatusCode = 12410
	CLASSROOM_INVITATION_ALREADY_INVITED         StatusCode = 12411
	CLASSROOM_INVITATION_TOKEN_INVALID           StatusCode = 12412
	CLASSROOM_INVITATION_TOKEN_GENERATION_FAILED StatusCode = 12413
	CLASSROOM_INVITATION_PERMISSION_DENIED       StatusCode = 12414

	// Classroom join request — user-initiated counterpart to the
	// teacher-initiated invitation flow. Same ma_classroom_members
	// table, distinguished by member_status = PENDING_REQUEST.
	CLASSROOM_JOIN_REQUEST_NOT_FOUND         StatusCode = 12501
	CLASSROOM_JOIN_REQUEST_NOT_PENDING       StatusCode = 12502
	CLASSROOM_JOIN_REQUEST_ALREADY_PENDING   StatusCode = 12503
	CLASSROOM_JOIN_REQUEST_PERMISSION_DENIED StatusCode = 12504

	// Classroom exercise — teacher-issued, AI-generated assignment
	// scoped to a classroom. Curriculum context (grade, program) is
	// derived from the classroom; chapter_name + lesson_name are the
	// teacher-supplied topic anchors fed to the bot.
	CLASSROOM_EXERCISE_NOT_FOUND                StatusCode = 12601
	CLASSROOM_EXERCISE_MISSING_ID               StatusCode = 12602
	CLASSROOM_EXERCISE_MISSING_CLASSROOM_ID     StatusCode = 12603
	CLASSROOM_EXERCISE_MISSING_TITLE            StatusCode = 12604
	CLASSROOM_EXERCISE_TITLE_TOO_LONG           StatusCode = 12605
	CLASSROOM_EXERCISE_MISSING_CHAPTER_NAME     StatusCode = 12606
	CLASSROOM_EXERCISE_CHAPTER_NAME_TOO_LONG    StatusCode = 12607
	CLASSROOM_EXERCISE_MISSING_LESSON_NAME      StatusCode = 12608
	CLASSROOM_EXERCISE_LESSON_NAME_TOO_LONG     StatusCode = 12609
	CLASSROOM_EXERCISE_INVALID_NUM_QUESTIONS    StatusCode = 12610
	CLASSROOM_EXERCISE_INVALID_DATE_RANGE       StatusCode = 12611
	CLASSROOM_EXERCISE_NOTE_TOO_LONG            StatusCode = 12612
	CLASSROOM_EXERCISE_INVALID_PROGRAM          StatusCode = 12613
	CLASSROOM_EXERCISE_PROGRAM_NOT_IN_CLASSROOM StatusCode = 12614
	CLASSROOM_EXERCISE_ALREADY_DELETED          StatusCode = 12615
	CLASSROOM_EXERCISE_PERMISSION_DENIED        StatusCode = 12616
	CLASSROOM_EXERCISE_GENERATION_FAILED        StatusCode = 12617
	CLASSROOM_EXERCISE_INVALID_VISIBILITY       StatusCode = 12618
	CLASSROOM_EXERCISE_PRIVATE_DENIED           StatusCode = 12619
	CLASSROOM_EXERCISE_INVALID_PURPOSE          StatusCode = 12620

	// Server lifecycle — 13000-13099
	SERVER_SHUTTING_DOWN StatusCode = 13001

	// Classroom exercise submissions — 12700-12799
	CLASSROOM_EXERCISE_SUBMISSION_NOT_FOUND            StatusCode = 12700
	CLASSROOM_EXERCISE_SUBMISSION_MISSING_ID           StatusCode = 12701
	CLASSROOM_EXERCISE_SUBMISSION_MISSING_EXERCISE_ID  StatusCode = 12702
	CLASSROOM_EXERCISE_SUBMISSION_MISSING_ANSWERS      StatusCode = 12703
	CLASSROOM_EXERCISE_SUBMISSION_INVALID_ANSWERS      StatusCode = 12704
	CLASSROOM_EXERCISE_SUBMISSION_ALREADY_EXISTS       StatusCode = 12705
	CLASSROOM_EXERCISE_SUBMISSION_WINDOW_NOT_OPEN      StatusCode = 12706
	CLASSROOM_EXERCISE_SUBMISSION_WINDOW_CLOSED        StatusCode = 12707
	CLASSROOM_EXERCISE_SUBMISSION_EXERCISE_UNAVAILABLE StatusCode = 12708
	CLASSROOM_EXERCISE_SUBMISSION_PERMISSION_DENIED    StatusCode = 12709
	CLASSROOM_EXERCISE_SUBMISSION_GRADING_FAILED       StatusCode = 12710
	CLASSROOM_EXERCISE_SUBMISSION_NOTE_TOO_LONG        StatusCode = 12711
	CLASSROOM_EXERCISE_SUBMISSION_ALREADY_DELETED      StatusCode = 12712

	// Home layout — 13100-13199
	HOME_MISSING_PROFILE_ID StatusCode = 13101
	HOME_PROFILE_NOT_FOUND  StatusCode = 13102
	HOME_PROFILE_NOT_OWNED  StatusCode = 13103
	HOME_UNSUPPORTED_ROLE   StatusCode = 13104

	// Socket / WebSocket — 13300-13399
	SOCKET_UNAUTHORIZED         StatusCode = 13300
	SOCKET_MISSING_TOPIC        StatusCode = 13301
	SOCKET_TOPIC_FORBIDDEN      StatusCode = 13302
	SOCKET_INVALID_MESSAGE      StatusCode = 13303
	SOCKET_TOO_MANY_CONNECTIONS StatusCode = 13304
	SOCKET_DISABLED             StatusCode = 13305
)
