package status

type StatusCode int

const (
	SUCCESS               StatusCode = 200
	CREATED               StatusCode = 201
	ACCEPTED              StatusCode = 202
	NO_DATA               StatusCode = 202
	NO_CONTENT            StatusCode = 204
	BAD_REQUEST           StatusCode = 400
	FAIL                  StatusCode = 400
	UNAUTHORIZED          StatusCode = 401
	FORBIDDEN             StatusCode = 403
	NOT_FOUND             StatusCode = 404
	CONFLICT              StatusCode = 409
	INTERNAL_SERVER_ERROR StatusCode = 500

	USER_MISSING_EMAIL        StatusCode = 4001
	USER_MISSING_PHONE        StatusCode = 4002
	USER_MISSING_PASSWORD     StatusCode = 4003
	USER_INVALID_EMAIL        StatusCode = 4004
	USER_INVALID_PASSWORD     StatusCode = 4005
	USER_NOT_FOUND            StatusCode = 4006
	USER_EMAIL_ALREADY_EXISTS StatusCode = 4007
	USER_PHONE_ALREADY_EXISTS StatusCode = 4008
	USER_ALREADY_EXISTS       StatusCode = 4009

	AUTH_MISSING_PHONE             StatusCode = 4201
	AUTH_MISSING_DEVICE_UUID       StatusCode = 4202
	AUTH_MISSING_IP_ADDRESS        StatusCode = 4203
	AUTH_MISSING_DEVICE_PUSH_TOKEN StatusCode = 4204
	AUTH_INVALID_TOKEN             StatusCode = 4205
	AUTH_LOGIN_FAILED              StatusCode = 4206
	AUTH_LOGOUT_FAILED             StatusCode = 4207

	PROFILE_NOT_FOUND            StatusCode = 4101
	PROFILE_MISSING_NAME         StatusCode = 4102
	PROFILE_MISSING_USER_ID      StatusCode = 4103
	PROFILE_MISSING_GRADE_ID     StatusCode = 4104
	PROFILE_MISSING_SEMESTER_ID  StatusCode = 4105
	PROFILE_INVALID_DOB          StatusCode = 4106
	PROFILE_AVATAR_INVALID_FILE  StatusCode = 4107
	PROFILE_AVATAR_UPLOAD_FAILED StatusCode = 4108
	PROFILE_MISSING_PROGRAM_ID   StatusCode = 4109
	PROFILE_INVALID_LANGUAGE     StatusCode = 4110

	PROGRAM_NOT_FOUND        StatusCode = 4301
	PROGRAM_INVALID_LANGUAGE StatusCode = 4302

	GRADE_NOT_FOUND        StatusCode = 4401
	GRADE_INVALID_LANGUAGE StatusCode = 4402

	SEMESTER_NOT_FOUND        StatusCode = 4501
	SEMESTER_INVALID_LANGUAGE StatusCode = 4502

	DEVICE_NOT_FOUND         StatusCode = 4601
	DEVICE_MISSING_UUID      StatusCode = 4602
	DEVICE_MISSING_NAME      StatusCode = 4603
	DEVICE_MISSING_USER_ID   StatusCode = 4604
	DEVICE_NOT_OWNED         StatusCode = 4605
	DEVICE_ALREADY_VERIFIED  StatusCode = 4606
	DEVICE_REGISTRATION_FAIL StatusCode = 4607
	DEVICE_VERIFICATION_FAIL StatusCode = 4608
	DEVICE_REVOKE_FAIL       StatusCode = 4609
	DEVICE_2FA_REQUIRED      StatusCode = 4610

	OTP_NOT_FOUND           StatusCode = 4701
	OTP_MISSING_TYPE        StatusCode = 4702
	OTP_MISSING_IDENTIFIER  StatusCode = 4703
	OTP_MISSING_CODE        StatusCode = 4704
	OTP_INVALID_TYPE        StatusCode = 4705
	OTP_INVALID_CODE        StatusCode = 4706
	OTP_EXPIRED             StatusCode = 4707
	OTP_ALREADY_VERIFIED    StatusCode = 4708
	OTP_REVOKED             StatusCode = 4709
	OTP_TOO_MANY_ATTEMPTS   StatusCode = 4710
	OTP_TOO_FREQUENT        StatusCode = 4711
	OTP_RATE_LIMITED        StatusCode = 4712
	OTP_DELIVERY_FAILED     StatusCode = 4713
	OTP_NO_DELIVERY_CHANNEL StatusCode = 4714
	OTP_GENERATION_FAILED   StatusCode = 4715

	NOTIFICATION_MISSING_UID        StatusCode = 5001
	NOTIFICATION_MISSING_TITLE      StatusCode = 5002
	NOTIFICATION_MISSING_SHORT_TEXT StatusCode = 5003
	NOTIFICATION_INVALID_ICON       StatusCode = 5004
	NOTIFICATION_INVALID_PRIORITY   StatusCode = 5005
	NOTIFICATION_NOT_FOUND          StatusCode = 5006

	MESSAGING_PUBLISH_FAILED   StatusCode = 6001
	MESSAGING_INVALID_ENVELOPE StatusCode = 6002
	MESSAGING_CONFIG_INVALID   StatusCode = 6003
	MESSAGING_CONNECT_FAILED   StatusCode = 6004

	CACHE_CONNECT_FAILED   StatusCode = 7001
	CACHE_CONFIG_INVALID   StatusCode = 7002
	CACHE_OP_FAILED        StatusCode = 7003
	CACHE_SERIALIZE_FAILED StatusCode = 7004

	STORAGE_CONFIG_INVALID StatusCode = 8001

	SMS_CONNECT_FAILED   StatusCode = 9001
	SMS_CONFIG_INVALID   StatusCode = 9002
	SMS_OP_FAILED        StatusCode = 9003
	SMS_SERIALIZE_FAILED StatusCode = 9004

	BOT_CONNECT_FAILED    StatusCode = 10001
	BOT_CONFIG_INVALID    StatusCode = 10002
	BOT_OP_FAILED         StatusCode = 10003
	BOT_SERIALIZE_FAILED  StatusCode = 10004
	BOT_INVALID_PROMPT    StatusCode = 10005
	BOT_CONTEXT_TOO_LARGE StatusCode = 10006
	BOT_RATE_LIMITED      StatusCode = 10007
	BOT_UNSUPPORTED_OP    StatusCode = 10008

	QUIZ_NOT_FOUND             StatusCode = 11001
	QUIZ_MISSING_PROFILE_ID    StatusCode = 11002
	QUIZ_MISSING_TYPE          StatusCode = 11003
	QUIZ_INVALID_TYPE          StatusCode = 11004
	QUIZ_INVALID_LANGUAGE      StatusCode = 11005
	QUIZ_MISSING_ANSWERS       StatusCode = 11006
	QUIZ_INVALID_ANSWERS       StatusCode = 11007
	QUIZ_ALREADY_SUBMITTED     StatusCode = 11008
	QUIZ_NOT_OWNED             StatusCode = 11009
	QUIZ_PREVIOUS_NOT_FOUND    StatusCode = 11010
	QUIZ_PREVIOUS_NOT_GRADED   StatusCode = 11011
	QUIZ_GENERATION_FAILED     StatusCode = 11012
	QUIZ_GRADING_FAILED        StatusCode = 11013
	QUIZ_PROFILE_NOT_CONFIGURED StatusCode = 11014

	JOB_NOT_FOUND            StatusCode = 12001
	JOB_ALREADY_PAUSED       StatusCode = 12002
	JOB_NOT_PAUSED           StatusCode = 12003
	JOB_IN_FLIGHT            StatusCode = 12004
	JOB_RUNTIME_UNAVAILABLE  StatusCode = 12005
	JOB_MISSING_NAME         StatusCode = 12006
	JOB_TRIGGER_FAILED       StatusCode = 12007
	TASK_HANDLER_NOT_FOUND   StatusCode = 12008
	TASK_QUEUE_FULL          StatusCode = 12009
	TASK_MISSING_NAME        StatusCode = 12010
	TASK_ENQUEUE_FAILED      StatusCode = 12011
)
